import { IRoute, Router } from "express";
import {getTodoList, createTodo,getTodo,updateTodo,  deleteTodo} from "../controllers/todoController";
import verifyUser from "../middlewares/verifyUser";
const route = Router();
route.get("/",verifyUser, getTodoList);
route.post("/",verifyUser, createTodo);
route.get("/:id",verifyUser,getTodo);
route.put("/:id",verifyUser, updateTodo);
route.delete("/:id",verifyUser, deleteTodo);
export default route;